defaults:
  - algorithm: pets
  - dynamics_model: gaussian_mlp_ensemble
  - overrides: pets_cartpole
  - action_optimizer: cem

device: "cuda:0"
log_frequency_agent: 1000
save_video: false
debug_mode: false

use_yuda_default: false
add_exp_to_replay_buffer: false
use_policy_buffer_adv_update: false

use_mbrl_demos: false
train_disc_in_model: false

disc_ensemble: true
disc_ensemble_reduction: "min"

disc_binary_reward: false

sac_schedule_lr: false
schedule_sac_ratio: true
sac_schedule:
  start_ratio: 0.5
  mid_ratio: 0.5
  end_ratio: 0.2
  m1: 20_000
  m2: 100_000

eval_frequency: 10000

silent: true
from_end: false
shaky: true
p_tremble: -1

relabel_samples: true
no_regret: false

train_discriminator: true
update_with_model: false
schedule_disc_special: false
n_discs: 7
disc:
  start_lr: 8e-4
  mid_lr: 8e-4
  end_lr: 8e-4
  m1: 30_000
  m2: 100_000
  batch_size: 4096
  freq_train_disc: 5000
  num_updates_per_step: 4
  num_traj_samples: 4

experiment: default
seed: 1


root_dir: "./exp"
hydra:
  run:
    dir: ${root_dir}/${algorithm.name}/${experiment}/${overrides.env}/${now:%m.%d}/${now:%H%M%S}-seed${seed}

  sweep:
    dir: ${root_dir}/${algorithm.name}/${experiment}/${overrides.env}/${now:%m.%d}/${now:%H%M%S}-seed${seed}